name: Auto Merge
on:
  pull_request:
    types:
      - labeled  # Merges PRs labeled 'automerge'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
